apiVersion: v1
data:
  FirstName: c2FtZWVyCg==
  LastName: c2hpbmRlCg==
  Password: UEA1NXdvcmQK
  Username: c2FtZWVyc2hpbmRlCg==
kind: Secret
metadata:
  name: ops-manager-admin-secret
  namespace: mongodb 
