rbac:
  enabled: true
ingress:
  enabled: true
serviceType: LoadBalancer
user:
  username: "root"
  email: "root@polyaxon.local"
  password: "rootpassword"
persistence:
  logs:
    existingClaim:
    mountPath: "/tmp/logs"
    hostPath: "/tmp/logs"
  repos:
    existingClaim:
    mountPath: "/tmp/repos"
    hostPath: "/tmp/repos"
  outputs:
    outputs:
      mountPath: "/tmp/outputs"
      hostPath: "/tmp/outputs"
  data:
    data:
      mountPath: "/tmp/data"
      hostPath: "/tmp/data"
email:
  host: "smtp.gmail.com"
  port: 587
  useTls: true
  hostUser: "foo"
  hostPassword: "bar"
hostName: polyaxon.foo.com
