apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ${kops_cluster_name}
  name: master-${kops_master_zones}
spec:
  associatePublicIp: ${kops_associate_public_ip}
  image: ${kops_master_image}
  machineType: ${kops_master_size}
  maxSize: ${kops_master_count_max}
  minSize: ${kops_master_count_min}
  nodeLabels:
    kops.k8s.io/instancegroup: ${kops_master_zones}
  role: Master
  rootVolumeSize: ${kops_master_volume_size}
  subnets:
  - ${kops_region}
  zones:
  - ${kops_master_zones}
