apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ${kops_cluster_name}
  name: nodes
spec:
  associatePublicIp: ${kops_associate_public_ip}
  image: ${kops_node_image}
  machineType: ${kops_node_size}
  maxSize: ${kops_node_count_max}
  minSize: ${kops_node_count_min}
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: ${kops_node_volume_size}
  subnets:
  - ${kops_region}
  zones:
  - ${kops_worker_zones}
