apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ${{kops_cluster_name}}
  name: nodes
spec:
  associatePublicIp: false
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: g1-small
  maxSize: 0
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 10
  subnets:
  - us-central1
  zones:
  - ${{kops_worker_zones}}
